### ISSUE TITLE
Unable to build application using VSO

### ISSUE THREAD

**Issue by rosieks** [Microsoft/taco-team-build#12]
I have tried to build my application using Visual Studio Online by following this document:

Unfortunately, build failed:

	Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\Gulp\0.5.3\Gulptask.ps1
	C:\NPM\Modules\gulp.cmd --gulpfile "C:\a\1\s\Locomotive\DataCollectorApp\gulpfile.js" 
	 Using gulpfile C:\a\1\s\Locomotive\DataCollectorApp\gulpfile.js
	 Starting 'scripts'...
	 Finished 'scripts' after 12 ms
	 Starting 'build'...
	Cordova version set to 5.3.1 based on the contents of taco.json
	Cordova cache found at C:\cordova\cli
	Installing Cordova 5.3.1.

	npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
	Exec complete.
	cordova@5.3.1 node_modules\cordova
	Γö£ΓöÇΓöÇ q@1.0.1
	Γö£ΓöÇΓöÇ underscore@1.7.0
	Γö£ΓöÇΓöÇ nopt@3.0.1 (abbrev@1.0.7)
	ΓööΓöÇΓöÇ cordova-lib@5.3.1 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.2.3, bplist-parser@0.0.6, unorm@1.3.3, shelljs@0.3.0, rc@0.5.2, semver@4.3.6, dep-graph@1.1.0, npmconf@2.1.2, xcode@0.8.0, init-package-json@1.9.1, elementtree@0.1.6, tar@1.0.2, glob@4.0.6, cordova-registry-mapper@1.1.13, request@2.47.0, cordova-serve@0.1.3, aliasify@1.8.0, cordova-js@4.1.1, plist@1.1.0, cordova-app-hello-world@3.9.0, npm@2.14.11)
	Adding support plugin.
	 'build' errored after 55 s
	 CordovaError: The provided path "C:\a\1\s\Locomotive\DataCollectorApp\platforms\android" is not an Android project.
		at new android_parser (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\cordova-lib\src\cordova\metadata\android_parser.js:35:15)
		at new PlatformProjectAdapter (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:61:19)
		at Object.getPlatformProject (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:97:23)
		at handleInstall (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:563:36)
		at C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:363:28
		at _fulfilled (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\q\q.js:787:54)
		at self.promiseDispatch.done (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\q\q.js:816:30)
		at Promise.promise.promiseDispatch (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\q\q.js:749:13)
		at C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\q\q.js:509:49
		at flush (C:\cordova\cli\5.3.1\node_modules\cordova\node_modules\q\q.js:108:17)

	Unexpected exit code 1 returned from tool gulp.cmd

**Comment by Chuxel** [comment]
Be sure to set your working directory under "Advanced" to the location of your Cordova project. That can cause this error.  Also, please use the version from http://aka.ms/tacoteambuild-rel or the taco-team-build npm package as the version in this git repo is currently in development.
