### ISSUE TITLE
init() fails to find cordova cache

### ISSUE THREAD

**Issue by gmaughan** [Microsoft/taco-team-build#14]
When using the Visual Studio Task Runner and "latest" version of taco-team-build. The Task Runner fails to read my gulpfile.js and gives the following output:

```
Failed to run "D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
Error: EPERM, operation not permitted 'C:\'
    at Object.fs.mkdirSync (fs.js:653:18)
    at D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:69:42
    at Array.forEach (native)
    at joinAndCreatePath (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:62:14)
    at ensurePathExists (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:57:12)
    at init (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:41:5)
    at Object.<anonymous> (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:43:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

When run from a command prompt I get:

```
fs.js:799
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Users'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:69:42
    at Array.forEach (native)
    at joinAndCreatePath (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:62:14)
    at ensurePathExists (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:57:12)
    at init (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:41:5)
    at Object.<anonymous> (D:\Projects\Hyper\MM_trunk_gulpbuild\MarkbookMobile\node_modules\taco-team-build\lib\ttb-util.js:43:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

I have attempted this with CORDOVA_CACHE both set and unset with the same results.

Using Visual Studio 2015.
Tools for Apache Cordova (latest)
Taco Team Build 0.2.0

**Comment by Chuxel** [comment]
Interesting - This does not repro from the command line so it is something very specific to Visual Studio. Will investigate.

**Comment by Chuxel** [comment]
For some reason VS doesn't like the modules use of fs.accessSync to determine if the directory exists.  Unfortunately the task runner explorer uses an older version of node so that could be the cause.  We should change fileExistsSync in ttb-util.js to the following:

function fileExistsSync(path) {
    try {
        var stats = fs.statSync(path);
        return (stats && stats.isDirectory());
    } catch (e) {
        return false;
    }
}

**Comment by gmaughan** [comment]
Thanks for looking into it @Chuxel 

I can confirm that running my gulp script from a standard Command Prompt works correctly. When loading the script in Task Runner or running it in a Visual Studio 2015 Command Prompt it does not work.

**Comment by ryuyu** [comment]
Should have been addressed with pull request 16 (https://github.com/Microsoft/taco-team-build/issues/16) and has been updated on npm. Please let us know if you continue to see this issue.
