### ISSUE TITLE
cordovaBuild.configure causing TypeError: pathList.forEach is not a function

### ISSUE THREAD

**Issue by rogerhaw** [Microsoft/taco-team-build#27]
running this task in a gulpfile gives me an error - I have the latest code from the repo.... thanks....

gulp.task("configure-cordova", function () {
   cordovaBuild.configure({
		nodePackageName: "cordova-cli",
		moduleCache: "C:\\BuildTest\\cordova-install\\",
		moduleVersion: "6.0.0"
	//	,
	 //   projectPath: "myproject"
     });
}); 

as follows:

[16:46:37] Starting 'configure-cordova'...
[16:46:37] 'configure-cordova' errored after 673 µs
[16:46:37] TypeError: pathList.forEach is not a function
    at joinAndCreatePath (C:\BuildTest\buildmob\node_modules\taco-team-build\lib\ttb-util.js:62:14)
    at Object.parseConfig (C:\BuildTest\buildmob\node_modules\taco-team-build\lib\ttb-util.js:169:22)
    at Object.configure (C:\BuildTest\buildmob\node_modules\taco-team-build\taco-team-build.js:29:31)
    at Gulp.<anonymous> (C:\BuildTest\buildmob\gulpfile.js:71:17)
    at module.exports (C:\BuildTest\buildmob\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\BuildTest\buildmob\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\BuildTest\buildmob\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\BuildTest\buildmob\node_modules\orchestrator\index.js:134:8)
    at C:\Users\msdnh_000\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)

**Comment by rogerhaw** [comment]
ok..found that the latest version was installed globally (as per Readme instructions) npm install -g c:\path\to\taco-team-build
but need to install locally
npm install c:\path\to\taco-team-build
to get latest version.
thx
